### ISSUE TITLE
Do actual photometry on simulated sources

### ISSUE THREAD

**Issue by mbaumer** [cpadavis/weak_sauce#15]
We want to get a handle on the photmetric bias and scatter caused by pixel area variations, but the adaptive moments code basically just integrates over the entire cutout (and divides by 2 for some reason...).

I'm implementing an alternative way to evaluate source parameters (mainly interested in flux) using [sewpy](http://sewpy.readthedocs.org/en/latest/)

**Comment by cpadavis** [comment]
awesome! I'm all in favor of something that can pull out photometries that
are more common.

I should point out though that unless you are explicitly fitting say a
seric profile to your object (or devac + expon), flux determination is
inherently a weighted integration procedure. mag_auto, for example,
computes a radius R1 = int r I d^2r / int I d^2r (with the 2d axes shifted
appropriately by the measured ellipticity as defined by the 2nd moments)
and then adds up all the flux out to 2.5 R1 (unweighted, I believe?).
Procedurally, this isn't _that_ different from the adaptive moments
approach, where the window function is a 2d elliptical gaussian instead of
a tophat.

**Comment by mbaumer** [comment]
cool--I wasn't actually sure how adaptive moments was computing the zeroth--this might not make much difference then, but they will at least be fluxes that people will recognize. By default the code runs with a 3x3 gaussian kernel, but we can pass alternative ones using `{'FILTER_NAME' : 'myfilter.txt'}` within the config kwarg if there's something better to be using:

From sewpy.py:

``` python
def _write_default_conv(self):
        """
        Writes the default convolution matrix, if needed.
        """

        if not os.path.exists(self._get_conv_filepath()):   
            f = open(self._get_conv_filepath(), 'w')
            f.write("""CONV NORM
# 3x3 ``all-ground'' convolution mask with FWHM = 2 pixels.
1 2 1
2 4 2
1 2 1""")
            f.close()
            logger.debug("Wrote %s" % (self._get_conv_filepath()))
        else:
            logger.debug("Default conv file already exists, I don't overwrite it.")
```

The only reason I was suspicious that the photometry might need improvement is that the photometric error hist was showing more scatter than we expected (see below). My guess was that it might be coming from summing over noisy (due to size variation) pixels away from the source...

![image](https://cloud.githubusercontent.com/assets/7607631/8852943/100bed2a-3150-11e5-8b99-7054bd899d37.png)
