### ISSUE TITLE
Fit vertices to data method

### ISSUE THREAD

**Issue by mbaumer** [cpadavis/weak_sauce#4]
should belong to MoveableGrid--takes in an ultraflat and returns a plausible vertex model.

**Comment by mbaumer** [comment]
Awesome job, Chris! This still needs a few features, like:
- [ ] letting L (aka local QE variation) float
- [x] some safety checks to prevent runaway solutions
  and potentially other things to be documented below...

**Comment by cpadavis** [comment]
reminder to myself that I have turned off the sorting lines of code in my fitter because it was actually messing up the fits. I am probably better off just checking vertex order when calculating areas and raise a warning there...

so some more todos after those above ones:
- [x] Add vertex order checker (make sure that vertices[i,:,0] < vertices[i+1,:,0], etc) that would be called during move_fluxes
- [x] Fix sorting code in move_vertices
- [ ] Fix derivative for luminosity (that part is clearly not correct because I get silly-large derivatives)
- [x] If I let local QE variation float, I should also add some kind of regularization for that variation

**Comment by mbaumer** [comment]
We've got a fitting method that works; let's track enhancements to it in other issues...
